// @ts-check
// Auto-generated by docs/deploy.sh - __SITE_NAME__ site

const { themes: prismThemes } = require('prism-react-renderer');

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: '__SITE_TITLE__',
  tagline: '__SITE_TAGLINE__',
  favicon: 'img/favicon.ico',

  url: 'https://__DOCS_DOMAIN__',
  baseUrl: '/__SITE_NAME__/',

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          // Docs become the root of the site (no /docs/ prefix in URLs)
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  plugins: [
    // Disable webpack-dev-server's HMR WebSocket client.
    // Traefik routes only /<sitename>/* paths, not the bare /ws path
    // webpack-dev-server uses by default - so the WebSocket handshake fails
    // and floods the browser console with errors. Live reload is handled by
    // the custom polling-based HotReloadToggle (⚡ LIVE button) instead.
    function disableHmrWebSocket() {
      return {
        name: 'disable-hmr-websocket',
        configureWebpack(_config, isServer) {
          if (isServer) return {};
          return {
            devServer: { client: false, hot: false, liveReload: false },
          };
        },
      };
    },
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: {
        defaultMode: 'dark',
        disableSwitch: false,
        respectPrefersColorScheme: true,
      },
      navbar: {
        title: '__SITE_TITLE__',
        style: 'dark',
        items: [
          { type: 'custom-hotReloadToggle', position: 'right' },
        ],
      },
      footer: {
        style: 'dark',
        copyright: `© ${new Date().getFullYear()} - Homelab Docs`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ['csharp', 'bash', 'json', 'yaml', 'powershell'],
      },
      tableOfContents: {
        minHeadingLevel: 2,
        maxHeadingLevel: 4,
      },
    }),
};

module.exports = config;
