#!/usr/bin/env bash
# ==============================================================================
# CPU Frequency Policy (governor + energy/performance preference)
# ==============================================================================
# Proxmox kernels default to the "performance" governor. With intel_pstate in
# HWP mode that pins each core's HWP request to min=max with EPP 0, so every
# wakeup runs at full boost. Depending on BIOS/microcode this can cost several
# watts at idle (measured on Arrow Lake: ~18 W package vs ~10 W with
# powersave + balance_power, for a mostly idle homelab host).
#
# Installs /usr/local/sbin/cpufreq-policy + a oneshot unit that applies the
# configured governor and EPP to every CPU at boot. Rewritten on every run so
# config changes take effect (single writer for these files).
#
# Config (proxmox-dr.env, optional):
#   CPU_GOVERNOR  - default: powersave
#   CPU_EPP       - default: balance_power
#                   (performance | balance_performance | balance_power | power)
# ==============================================================================

readonly CPUFREQ_POLICY_SCRIPT="/usr/local/sbin/cpufreq-policy"
readonly CPUFREQ_POLICY_UNIT="/etc/systemd/system/cpufreq-policy.service"

# ==============================================================================
# Main Entry Point - called from proxmox-dr/run-setup.sh::execute_proxmox_setup
# ==============================================================================

setup_cpufreq_policy() {
    log_section "Configuring CPU Frequency Policy"

    local governor="${CPU_GOVERNOR:-powersave}"
    local epp="${CPU_EPP:-balance_power}"

    if [[ ! -r /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors ]]; then
        log_warn "No cpufreq driver on this host - skipping CPU frequency policy"
        return 0
    fi

    if ! grep -qw "$governor" /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors; then
        log_error "Governor '${governor}' not available (have: $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors))"
        return 1
    fi

    write_cpufreq_policy_script "$governor" "$epp"
    write_cpufreq_policy_unit
    enable_cpufreq_policy_unit

    local active_gov active_epp
    active_gov=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
    active_epp=$(cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference 2>/dev/null || echo n/a)
    log_info "✓ CPU policy active: governor=${active_gov}, EPP=${active_epp}"
}

# ==============================================================================
# Implementation
# ==============================================================================

write_cpufreq_policy_script() {
    local governor="$1"
    local epp="$2"

    mkdir -p "$(dirname "$CPUFREQ_POLICY_SCRIPT")"
    cat > "$CPUFREQ_POLICY_SCRIPT" << EOF
#!/bin/sh
# Applies CPU governor + EPP to every CPU. Generated by proxmox-dr IaC
# (lib/24-cpufreq.sh) - edit proxmox-dr.env and re-run, not this file.
GOVERNOR="${governor}"
EPP="${epp}"

for cpu in /sys/devices/system/cpu/cpu[0-9]*/cpufreq; do
    echo "\$GOVERNOR" > "\$cpu/scaling_governor" || exit 1
    # EPP only exists with intel_pstate/amd-pstate in active (HWP/CPPC) mode,
    # and the kernel rejects EPP writes under the performance governor.
    if [ -w "\$cpu/energy_performance_preference" ] && [ "\$GOVERNOR" != "performance" ]; then
        echo "\$EPP" > "\$cpu/energy_performance_preference" || exit 1
    fi
done
EOF
    chmod 755 "$CPUFREQ_POLICY_SCRIPT"
    log_info "Wrote ${CPUFREQ_POLICY_SCRIPT} (governor=${governor}, EPP=${epp})"
}

write_cpufreq_policy_unit() {
    cat > "$CPUFREQ_POLICY_UNIT" << EOF
[Unit]
Description=Apply CPU frequency governor and energy/performance preference

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=${CPUFREQ_POLICY_SCRIPT}

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
}

enable_cpufreq_policy_unit() {
    systemctl enable cpufreq-policy.service >/dev/null 2>&1
    # restart (not start) so a re-run applies changed values immediately
    systemctl restart cpufreq-policy.service
}
