#!/usr/bin/env bash
# ==============================================================================
# NAS Mount Healing - Proxmox Host
# ==============================================================================
# Installs a systemd timer + small recovery script that, on every boot and
# every minute thereafter, retries:
#   1. Failed CIFS/NFS .mount/.automount units (the rate-limited-at-boot ones)
#   2. Failed pve-container@<ID>.service units that gave up because they had
#      RequiresMountsFor= on a mount that hadn't come up yet
#   3. Failed docker.service (in case anything Docker-side is on the host)
#
# Pairs with RequiresMountsFor= drop-ins on pve-container@<ID>.service for
# every LXC that has /mnt bind mounts. Those drop-ins are written by
# setup_bind_mount() in services/lib/lxc-service.sh at deploy time, not here.
#
# IMPORTANT: the systemd unit content here is a near-copy of what
# services/lib/heal-nas-mounts.sh installs in VMs. Keep them in sync - they
# implement the same logic and should change together.
# ==============================================================================

# ==============================================================================
# Main Entry Point - called from proxmox-dr/run-setup.sh::execute_proxmox_setup
# ==============================================================================

setup_heal_nas_mounts() {
    log_section "Installing NAS Mount Healing Timer"

    write_heal_nas_mounts_script
    write_heal_nas_mounts_units
    enable_heal_nas_mounts_timer

    log_info "heal-nas-mounts.timer installed and active"
}

# ==============================================================================
# Implementation
# ==============================================================================

write_heal_nas_mounts_script() {
    mkdir -p /usr/local/sbin

    cat > /usr/local/sbin/heal-nas-mounts <<'SCRIPT'
#!/bin/bash
# ----------------------------------------------------------------------
# heal-nas-mounts: periodically retry failed NAS mounts and any services
# that gave up because they were waiting on those mounts.
# Idempotent. Runs every minute via heal-nas-mounts.timer.
# Generated by IaC - do not edit on the host.
# ----------------------------------------------------------------------
set -uo pipefail

reset_and_start() {
    systemctl reset-failed "$1" 2>/dev/null || true
    systemctl start "$1" 2>/dev/null || true
}

# 1. Failed mount / automount units
systemctl list-units --state=failed --type=mount,automount --plain --no-legend 2>/dev/null \
    | awk '{print $1}' \
    | while read -r unit; do
        [ -n "$unit" ] && reset_and_start "$unit"
    done

# 2. Failed services that depend on NAS mounts
for svc in docker.service; do
    systemctl is-failed "$svc" >/dev/null 2>&1 && reset_and_start "$svc"
done

# 3. On Proxmox: pve-container@<ID>.service units that gave up
if command -v pct >/dev/null 2>&1; then
    systemctl list-units 'pve-container@*.service' --state=failed --plain --no-legend 2>/dev/null \
        | awk '{print $1}' \
        | while read -r unit; do
            [ -n "$unit" ] && reset_and_start "$unit"
        done
fi
SCRIPT

    chmod 755 /usr/local/sbin/heal-nas-mounts
    log_info "Wrote /usr/local/sbin/heal-nas-mounts"
}

write_heal_nas_mounts_units() {
    cat > /etc/systemd/system/heal-nas-mounts.service <<'SERVICE'
[Unit]
Description=Heal failed NAS mounts and dependent services
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/heal-nas-mounts
SERVICE

    cat > /etc/systemd/system/heal-nas-mounts.timer <<'TIMER'
[Unit]
Description=Periodically retry failed NAS mounts and dependent services

[Timer]
OnBootSec=30s
OnUnitActiveSec=1min
Persistent=true

[Install]
WantedBy=timers.target
TIMER

    log_info "Wrote heal-nas-mounts.service and heal-nas-mounts.timer"
}

enable_heal_nas_mounts_timer() {
    systemctl daemon-reload
    systemctl enable --now heal-nas-mounts.timer
    log_info "Enabled and started heal-nas-mounts.timer"
}
