#!/usr/bin/env bash
# ==============================================================================
# heal-nas-mounts library
# ==============================================================================
# Provides a systemd timer + small recovery script that, on any host with
# CIFS/NFS mounts, periodically:
#   1. Resets and retries failed .mount / .automount units
#   2. Resets and retries dependent services (docker.service, pve-container@*)
#      that were marked failed because they had RequiresMountsFor= on a mount
#      that wasn't up yet
#
# Pairs with RequiresMountsFor= drop-ins on docker.service (VMs) and on
# pve-container@<CT>.service (Proxmox host LXCs) so those services literally
# wait for the mounts before starting. The timer recovers transient NAS-at-
# boot failures so RequiresMountsFor doesn't permanently block startup.
#
# Functions:
#   setup_vm_nas_mount_resilience <path> [<path>...]
#     Installs the heal-nas-mounts timer in the VM AND writes the
#     docker.service drop-in with RequiresMountsFor=<paths>. Calls ssh_vm
#     (must be in scope - sourced from vm-service.sh).
#
# NOTE: proxmox-dr/lib/45-heal-nas-mounts.sh holds the equivalent install
# logic for the proxmox-dr deploy flow. The unit and script content must
# match between the two files - keep them in sync.
# ==============================================================================

# ------------------------------------------------------------------------------
# setup_vm_nas_mount_resilience <mount_path> [<mount_path>...]
# ------------------------------------------------------------------------------
# In one SSH session into the VM:
#   1. Installs /usr/local/sbin/heal-nas-mounts + .service + .timer
#   2. Writes /etc/systemd/system/docker.service.d/wait-for-nas.conf with
#      RequiresMountsFor=<mount_path>... so docker.service blocks until the
#      listed NAS mounts are active.
# ------------------------------------------------------------------------------
setup_vm_nas_mount_resilience() {
    local mounts="$*"

    if [[ -z "$mounts" ]]; then
        log_error "setup_vm_nas_mount_resilience: requires at least one mount path"
        return 1
    fi

    log_info "Installing heal-nas-mounts + docker mount-wait drop-in in VM..."
    log_info "  RequiresMountsFor: ${mounts}"

    ssh_vm "
set -euo pipefail

cat > /usr/local/sbin/heal-nas-mounts <<'SCRIPT'
#!/bin/bash
# heal-nas-mounts: periodically retry failed NAS mounts and any services
# that gave up because they were waiting on those mounts. Idempotent.
# Runs every minute via heal-nas-mounts.timer. Generated by IaC.
set -uo pipefail

reset_and_start() {
    systemctl reset-failed \"\$1\" 2>/dev/null || true
    systemctl start \"\$1\" 2>/dev/null || true
}

systemctl list-units --state=failed --type=mount,automount --plain --no-legend 2>/dev/null \\
    | awk '{print \$1}' \\
    | while read -r unit; do
        [ -n \"\$unit\" ] && reset_and_start \"\$unit\"
    done

for svc in docker.service; do
    systemctl is-failed \"\$svc\" >/dev/null 2>&1 && reset_and_start \"\$svc\"
done
SCRIPT
chmod 755 /usr/local/sbin/heal-nas-mounts

cat > /etc/systemd/system/heal-nas-mounts.service <<'SERVICE'
[Unit]
Description=Heal failed NAS mounts and dependent services
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/heal-nas-mounts
SERVICE

cat > /etc/systemd/system/heal-nas-mounts.timer <<'TIMER'
[Unit]
Description=Periodically retry failed NAS mounts and dependent services

[Timer]
OnBootSec=30s
OnUnitActiveSec=1min
Persistent=true

[Install]
WantedBy=timers.target
TIMER

mkdir -p /etc/systemd/system/docker.service.d
cat > /etc/systemd/system/docker.service.d/wait-for-nas.conf <<EOF
# Block docker.service until NAS mounts that its containers bind-mount are
# actually active. Generated by IaC; pairs with heal-nas-mounts timer.
[Unit]
RequiresMountsFor=${mounts}
EOF

systemctl daemon-reload
systemctl enable --now heal-nas-mounts.timer
"
    log_info "heal-nas-mounts installed; docker.service now waits for: ${mounts}"
}
